import { describe, expect, it } from 'vitest';

import {
  CHAPTER_MASK,
  LFSR_ORDINALS,
  LFSR_SEQUENCE,
  NIBBLE_MASK,
  O_INDEX_MASK,
  PAGE_MASK,
  PC_MASK,
  PC_STATE_COUNT,
  RESET_CHAPTER,
  RESET_PAGE,
  RESET_PC,
  RESET_ROM_ADDRESS,
  ROM_WORD_COUNT,
  R_MASK,
  R_OUTPUT_COUNT,
  SR_MASK,
  Tms1370Registers,
  X_MASK,
  ordinalForPc,
  pcForOrdinal,
  romAddress,
  stepProgramCounter,
} from './registers.js';

/**
 * The 64 physical word offsets a page is walked in, transcribed verbatim from
 * `docs/research/tms1370-architecture.md` §2 ("The program counter is an LFSR,
 * not a counter"), which computes them from MAME `tms1k_base.cpp:324-337`.
 *
 * This literal is the point of the test. `LFSR_SEQUENCE` is generated by
 * `stepProgramCounter`, so checking the table against its own generator would
 * pass for any stepping rule at all - including a rule that reaches only 62 of
 * the 64 states, which is the shape of error this comparison exists to catch.
 * The table below comes from outside the module.
 */
const DOCUMENTED_LFSR_SEQUENCE = [
  0x00, 0x01, 0x03, 0x07, 0x0f, 0x1f, 0x3f, 0x3e, 0x3d, 0x3b, 0x37, 0x2f, 0x1e, 0x3c, 0x39, 0x33,
  0x27, 0x0e, 0x1d, 0x3a, 0x35, 0x2b, 0x16, 0x2c, 0x18, 0x30, 0x21, 0x02, 0x05, 0x0b, 0x17, 0x2e,
  0x1c, 0x38, 0x31, 0x23, 0x06, 0x0d, 0x1b, 0x36, 0x2d, 0x1a, 0x34, 0x29, 0x12, 0x24, 0x08, 0x11,
  0x22, 0x04, 0x09, 0x13, 0x26, 0x0c, 0x19, 0x32, 0x25, 0x0a, 0x15, 0x2a, 0x14, 0x28, 0x10, 0x20,
];

/** Every 6-bit state, in numeric order - the shape a plain counter would walk. */
const ALL_STATES = Array.from({ length: PC_STATE_COUNT }, (_, index) => index);

describe('TMS1370 program counter LFSR', () => {
  it('walks the 64 word offsets the architecture document records', () => {
    expect(DOCUMENTED_LFSR_SEQUENCE).toHaveLength(PC_STATE_COUNT);
    expect(Array.from(LFSR_SEQUENCE)).toEqual(DOCUMENTED_LFSR_SEQUENCE);
  });

  it('is a bijection over its 64 states', () => {
    // Every state appears exactly once in the walk...
    expect(new Set(LFSR_SEQUENCE).size).toBe(PC_STATE_COUNT);
    expect([...LFSR_SEQUENCE].sort((a, b) => a - b)).toEqual(ALL_STATES);

    // ...and the stepping function itself is injective over the whole state
    // space, not just over the states the walk from 0 happens to reach. A rule
    // whose orbit from 0 is short would still pass a walk-only check if the
    // walk were truncated; this one cannot.
    const images = ALL_STATES.map((state) => stepProgramCounter(state));
    expect(new Set(images).size).toBe(PC_STATE_COUNT);
    expect([...images].sort((a, b) => a - b)).toEqual(ALL_STATES);
  });

  it('closes into a single cycle of length 64, with no shorter orbit', () => {
    let pc = RESET_PC;
    const visited: number[] = [];
    for (let step = 0; step < PC_STATE_COUNT; step += 1) {
      visited.push(pc);
      pc = stepProgramCounter(pc);
      expect(pc === RESET_PC).toBe(step === PC_STATE_COUNT - 1);
    }
    expect(new Set(visited).size).toBe(PC_STATE_COUNT);
  });

  it('is not a sequential counter', () => {
    // The guard the acceptance contract cares about: a core that quietly kept a
    // sequential program counter would satisfy "64 states" and "bijection" and
    // fail here. The n-th instruction of a page is not at offset n.
    expect(Array.from(LFSR_SEQUENCE)).not.toEqual(ALL_STATES);

    const fixedPoints = LFSR_SEQUENCE.filter((state, ordinal) => state === ordinal);
    expect(fixedPoints.length).toBeLessThan(PC_STATE_COUNT / 8);

    // Two concrete placements from the documented table, in both directions.
    expect(pcForOrdinal(7)).toBe(0x3e);
    expect(ordinalForPc(7)).toBe(3);
  });

  it('exports an exact inverse of the placement table', () => {
    expect(LFSR_ORDINALS).toHaveLength(PC_STATE_COUNT);
    for (const ordinal of ALL_STATES) {
      expect(ordinalForPc(pcForOrdinal(ordinal))).toBe(ordinal);
    }
    for (const state of ALL_STATES) {
      expect(pcForOrdinal(ordinalForPc(state))).toBe(state);
    }
  });

  it('resumes the documented order from a branch target loaded as a raw state', () => {
    // A branch operand is an LFSR state, not an instruction ordinal: the low six
    // opcode bits go into the shift register as-is (research doc §2). So loading
    // any state must continue the same walk from that state's position.
    for (let ordinal = 0; ordinal < PC_STATE_COUNT - 1; ordinal += 1) {
      const registers = new Tms1370Registers();
      registers.pc = DOCUMENTED_LFSR_SEQUENCE[ordinal] as number;
      registers.stepPc();
      expect(registers.pc).toBe(DOCUMENTED_LFSR_SEQUENCE[ordinal + 1]);
    }
  });

  it('masks its input to six bits', () => {
    for (const state of ALL_STATES) {
      expect(stepProgramCounter(state | 0x7c0)).toBe(stepProgramCounter(state));
    }
  });

  it('indexes the placement tables modulo the page size', () => {
    expect(pcForOrdinal(PC_STATE_COUNT + 5)).toBe(pcForOrdinal(5));
    expect(ordinalForPc(PC_STATE_COUNT + 5)).toBe(ordinalForPc(5));
  });
});

describe('TMS1370 ROM addressing', () => {
  it('composes an address as CA:PA:PC', () => {
    expect(romAddress(0, 0, 0)).toBe(0x000);
    expect(romAddress(0, 1, 0)).toBe(0x040);
    expect(romAddress(0, 15, 0)).toBe(0x3c0);
    expect(romAddress(1, 0, 0)).toBe(0x400);
    expect(romAddress(1, 15, 0x3f)).toBe(0x7ff);
  });

  it('spans 2048 words', () => {
    expect(ROM_WORD_COUNT).toBe(2048);
  });

  it('masks each field to its hardware width', () => {
    expect(romAddress(0xff, 0xff, 0xff)).toBe(0x7ff);
  });

  it('places the reset vector at 0x3C0', () => {
    // Composed from the reset chapter/page/PC rather than asserted as a stored
    // literal, so this checks the composition as well as the value.
    expect(RESET_ROM_ADDRESS).toBe(0x3c0);
    expect(RESET_CHAPTER).toBe(0);
    expect(RESET_PAGE).toBe(15);
    expect(RESET_PC).toBe(0);
  });
});

describe('TMS1370 register widths', () => {
  it('holds X in three bits, not four', () => {
    // The TMS1100 core's X selects one of eight RAM files. The HMCS44 core this
    // replaces used wider RAM pointers, so a 4-bit X here would be the clearest
    // possible sign of the old core wearing the new core's name.
    expect(X_MASK).toBe(0x07);
    const registers = new Tms1370Registers();
    registers.x = 0x0f;
    expect(registers.x).toBe(0x07);
    registers.x = 0x08;
    expect(registers.x).toBe(0x00);
  });

  it('holds A and Y in four bits', () => {
    const registers = new Tms1370Registers();
    registers.a = 0x1f;
    registers.y = 0x1f;
    expect(registers.a).toBe(NIBBLE_MASK);
    expect(registers.y).toBe(NIBBLE_MASK);
  });

  it('holds PA and PB in four bits', () => {
    const registers = new Tms1370Registers();
    registers.pa = 0x1f;
    registers.pb = 0x2a;
    expect(registers.pa).toBe(PAGE_MASK);
    expect(registers.pb).toBe(0x0a);
  });

  it('holds CA, CB, CS, status, the status latch and the call latch in one bit', () => {
    const registers = new Tms1370Registers();
    registers.ca = 0x03;
    registers.cb = 0x02;
    registers.cs = 0x03;
    registers.status = 0x02;
    registers.statusLatch = 0x03;
    registers.callLatch = 0x06;
    expect(registers.ca).toBe(1);
    expect(registers.cb).toBe(0);
    expect(registers.cs).toBe(1);
    expect(registers.status).toBe(0);
    expect(registers.statusLatch).toBe(1);
    expect(registers.callLatch).toBe(0);
    expect(CHAPTER_MASK).toBe(1);
  });

  it('holds the program counter in six bits', () => {
    const registers = new Tms1370Registers();
    registers.pc = 0xff;
    expect(registers.pc).toBe(PC_MASK);
  });

  it('holds one six-bit subroutine return word, not a stack', () => {
    // One level: SR is the return *word*, six bits wide. The return page is PB.
    expect(SR_MASK).toBe(PC_MASK);
    const registers = new Tms1370Registers();
    registers.sr = 0xff;
    expect(registers.sr).toBe(PC_MASK);
  });

  it('latches sixteen R outputs', () => {
    expect(R_OUTPUT_COUNT).toBe(16);
    expect(R_MASK).toBe(0xffff);
    const registers = new Tms1370Registers();
    registers.r = 0x1ffff;
    expect(registers.r).toBe(0xffff);
  });
});

describe('TMS1370 R output latches', () => {
  it('sets and resets each of the sixteen outputs individually', () => {
    const registers = new Tms1370Registers();
    for (let index = 0; index < R_OUTPUT_COUNT; index += 1) {
      registers.setR(index, true);
      expect(registers.getR(index)).toBe(true);
      expect(registers.r).toBe(1 << index);
      registers.setR(index, false);
      expect(registers.getR(index)).toBe(false);
      expect(registers.r).toBe(0);
    }
  });

  it('ignores indices outside the sixteen the package brings out', () => {
    const registers = new Tms1370Registers();
    registers.setR(R_OUTPUT_COUNT, true);
    registers.setR(-1, true);
    expect(registers.r).toBe(0);
    expect(registers.getR(R_OUTPUT_COUNT)).toBe(false);
    expect(registers.getR(-1)).toBe(false);
  });
});

describe('TMS1370 O register index', () => {
  it('is the status latch above the accumulator, five bits wide', () => {
    const registers = new Tms1370Registers();
    registers.a = 0x0d;
    registers.statusLatch = 0;
    expect(registers.oIndex).toBe(0x0d);
    registers.statusLatch = 1;
    expect(registers.oIndex).toBe(0x1d);
    expect(registers.oIndex & ~O_INDEX_MASK).toBe(0);
  });
});

describe('TMS1370 reset', () => {
  /** A register file with every field driven away from its reset value. */
  function dirtied(): Tms1370Registers {
    const registers = new Tms1370Registers();
    registers.a = 0x0a;
    registers.x = 0x05;
    registers.y = 0x0c;
    registers.status = 1;
    registers.statusLatch = 1;
    registers.callLatch = 1;
    registers.pa = 0x03;
    registers.pb = 0x07;
    registers.ca = 1;
    registers.cb = 1;
    registers.pc = 0x2b;
    registers.sr = 0x1a;
    registers.cs = 1;
    registers.r = 0xbeef;
    return registers;
  }

  it('enters at chapter 0, page 15, PC 0 - physical address 0x3C0', () => {
    const registers = dirtied();
    registers.reset();
    expect(registers.ca).toBe(0);
    expect(registers.pa).toBe(15);
    expect(registers.pc).toBe(0);
    expect(registers.romAddress).toBe(RESET_ROM_ADDRESS);
    expect(registers.romAddress).toBe(0x3c0);
  });

  it('clears the R outputs', () => {
    const registers = dirtied();
    registers.reset();
    expect(registers.r).toBe(0);
    for (let index = 0; index < R_OUTPUT_COUNT; index += 1) {
      expect(registers.getR(index)).toBe(false);
    }
  });

  it('clears status and the status latch, so the O register is written with index 0', () => {
    const registers = dirtied();
    registers.reset();
    expect(registers.status).toBe(0);
    expect(registers.statusLatch).toBe(0);
    expect(registers.oIndex).toBe(0);
  });

  it('clears the call latch and the subroutine return state', () => {
    const registers = dirtied();
    registers.reset();
    expect(registers.callLatch).toBe(0);
    expect(registers.inSubroutine).toBe(false);
    expect(registers.sr).toBe(0);
    expect(registers.cs).toBe(0);
  });

  it('loads the page and chapter buffers with the entry page and chapter', () => {
    const registers = dirtied();
    registers.reset();
    expect(registers.pb).toBe(15);
    expect(registers.cb).toBe(0);
  });

  it('clears the data registers', () => {
    const registers = dirtied();
    registers.reset();
    expect(registers.a).toBe(0);
    expect(registers.x).toBe(0);
    expect(registers.y).toBe(0);
  });

  it('leaves a freshly constructed register file in the reset state', () => {
    const constructed = new Tms1370Registers();
    const reset = dirtied();
    reset.reset();
    expect(constructed.snapshot()).toEqual(reset.snapshot());
  });
});

describe('TMS1370 one-level subroutine return', () => {
  it('latches the return word, the chapter and the call latch on entry', () => {
    const registers = new Tms1370Registers();
    registers.ca = 1;
    expect(registers.saveReturnState(0x2b)).toBe(true);
    expect(registers.sr).toBe(0x2b);
    expect(registers.cs).toBe(1);
    expect(registers.callLatch).toBe(1);
    expect(registers.inSubroutine).toBe(true);
  });

  it('saves nothing on a call taken inside a subroutine', () => {
    // The one-level stack asserted as a capability, not as a value: there is no
    // second slot to write, so the outer return address survives untouched and
    // the inner one is simply lost. A four-deep stack would fail here.
    const registers = new Tms1370Registers();
    registers.saveReturnState(0x2b);
    expect(registers.saveReturnState(0x15)).toBe(false);
    expect(registers.sr).toBe(0x2b);
    expect(registers.callLatch).toBe(1);
  });

  it('leaves the subroutine after a single return, however many calls were taken', () => {
    const registers = new Tms1370Registers();
    registers.saveReturnState(0x2b);
    registers.saveReturnState(0x15);
    registers.saveReturnState(0x09);
    expect(registers.restoreReturnState()).toBe(true);
    expect(registers.inSubroutine).toBe(false);
    expect(registers.pc).toBe(0x2b);
  });

  it('restores the program counter and chapter on return', () => {
    const registers = new Tms1370Registers();
    registers.ca = 1;
    registers.saveReturnState(0x2b);
    registers.ca = 0;
    registers.pc = 0x07;
    expect(registers.restoreReturnState()).toBe(true);
    expect(registers.pc).toBe(0x2b);
    expect(registers.ca).toBe(1);
    expect(registers.callLatch).toBe(0);
  });

  it('restores no program counter on a return taken outside a subroutine', () => {
    const registers = new Tms1370Registers();
    registers.pc = 0x07;
    expect(registers.restoreReturnState()).toBe(false);
    expect(registers.pc).toBe(0x07);
    expect(registers.callLatch).toBe(0);
  });

  it('reads the return page out of the page buffer', () => {
    // PB doubles as the return page: there is no separate register, which is
    // why LDP inside a subroutine destroys the return page.
    const registers = new Tms1370Registers();
    registers.pa = 0x06;
    expect(registers.returnPage).toBeNull();

    registers.saveReturnState(0x2b);
    registers.pb = registers.pa;
    registers.pa = 0x0c;
    expect(registers.returnPage).toBe(0x06);

    registers.pb = 0x02;
    expect(registers.returnPage).toBe(0x02);

    registers.restoreReturnState();
    expect(registers.returnPage).toBeNull();
  });
});

describe('TMS1370 register snapshot', () => {
  it('reports every register and the composed ROM address', () => {
    const registers = new Tms1370Registers();
    registers.a = 0x09;
    registers.x = 0x05;
    registers.y = 0x03;
    registers.status = 1;
    registers.statusLatch = 1;
    registers.callLatch = 1;
    registers.pa = 0x02;
    registers.pb = 0x0e;
    registers.ca = 1;
    registers.cb = 1;
    registers.pc = 0x2b;
    registers.sr = 0x16;
    registers.cs = 1;
    registers.r = 0x8001;

    expect(registers.snapshot()).toEqual({
      a: 0x09,
      x: 0x05,
      y: 0x03,
      status: 1,
      statusLatch: 1,
      callLatch: 1,
      pa: 0x02,
      pb: 0x0e,
      ca: 1,
      cb: 1,
      pc: 0x2b,
      sr: 0x16,
      cs: 1,
      r: 0x8001,
      romAddress: romAddress(1, 0x02, 0x2b),
    });
  });

  it('does not change when the register file is mutated afterwards', () => {
    const registers = new Tms1370Registers();
    const before = registers.snapshot();
    registers.a = 0x0f;
    expect(before.a).toBe(0);
  });
});
